// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package nftrace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfTraceInfo struct {
	Id          uint32
	Type        uint32
	TableName   [64]uint8
	TableHandle uint64
	ChainName   [64]uint8
	ChainHandle uint64
	RuleHandle  uint64
	JumpTarget  [64]uint8
	Verdict     uint32
	Family      int32
	Nfproto     uint8
	Policy      uint8
	Len         uint16
	Mark        uint32
	Iif         uint32
	Oif         uint32
	IifType     uint16
	OifType     uint16
	IifName     [16]uint8
	OifName     [16]uint8
	SrcPort     uint16
	DstPort     uint16
	SrcIp       uint32
	DstIp       uint32
	SrcIp6      struct{ In6U struct{ U6Addr8 [16]uint8 } }
	DstIp6      struct{ In6U struct{ U6Addr8 [16]uint8 } }
	SrcMac      [6]uint8
	DstMac      [6]uint8
	IpProto     uint8
	_           [3]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeNftTraceNotify *ebpf.ProgramSpec `ebpf:"kprobe_nft_trace_notify"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	SampleRate  *ebpf.MapSpec `ebpf:"sample_rate"`
	TraceCount  *ebpf.MapSpec `ebpf:"trace_count"`
	TraceHolder *ebpf.MapSpec `ebpf:"trace_holder"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	SampleRate  *ebpf.Map `ebpf:"sample_rate"`
	TraceCount  *ebpf.Map `ebpf:"trace_count"`
	TraceHolder *ebpf.Map `ebpf:"trace_holder"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.SampleRate,
		m.TraceCount,
		m.TraceHolder,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeNftTraceNotify *ebpf.Program `ebpf:"kprobe_nft_trace_notify"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeNftTraceNotify,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
